import { WorkflowTemplate } from '../src/types';

export const WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'hn-top-stories',
    title: 'Hacker News Top Stories',
    description: 'Navigate to Hacker News, extract the top 5 trending tech articles, their authors, points, and discussion link counts.',
    icon: 'Flame',
    category: 'scraping',
    initialUrl: 'https://news.ycombinator.com',
    goal: 'Navigate to Hacker News (news.ycombinator.com), extract the top 5 stories with their title, score points, submitter, and discuss comments count, and present them in a clean summary.',
    tags: ['Tech News', 'Scraping', 'Aggregator'],
  },
  {
    id: 'wikipedia-deep-dive',
    title: 'Wikipedia Research & Milestone Extractor',
    description: 'Search Wikipedia for Quantum Computing or Artificial Intelligence, navigate to the main article, and extract key milestones and foundational principles.',
    icon: 'BookOpen',
    category: 'research',
    initialUrl: 'https://en.wikipedia.org',
    goal: 'Open Wikipedia (en.wikipedia.org), search for "Quantum computing", navigate to the article, and extract a comprehensive summary of its key physical principles and historical timeline.',
    tags: ['Research', 'Knowledge', 'Wikipedia'],
  },
  {
    id: 'ecommerce-finder',
    title: 'Books & Pricing Comparator',
    description: 'Navigate to books.toscrape.com, find top-rated fiction books, extract titles, star ratings, and prices.',
    icon: 'ShoppingBag',
    category: 'scraping',
    initialUrl: 'https://books.toscrape.com',
    goal: 'Navigate to books.toscrape.com, browse the catalog, find the top 5 Five-Star rated books, extract their title, price, and in-stock status.',
    tags: ['E-commerce', 'Price Comparison', 'Catalog'],
  },
  {
    id: 'form-qa-automation',
    title: 'Interactive Form & Search Automation',
    description: 'Test filling forms, selecting dropdowns, triggering search queries, and verifying rendered results.',
    icon: 'CheckSquare',
    category: 'qa',
    initialUrl: 'https://duckduckgo.com',
    goal: 'Go to DuckDuckGo, search for "Latest developments in humanoid robotics 2026", click the first authoritative news link, and summarize the article.',
    tags: ['QA & Testing', 'Search', 'Form Filling'],
  },
  {
    id: 'a11y-seo-audit',
    title: 'A11y & Structure Inspector',
    description: 'Audit any web page accessibility tree, check ARIA roles, find broken headings, and verify interactive element refs.',
    icon: 'Eye',
    category: 'monitoring',
    initialUrl: 'https://example.com',
    goal: 'Inspect the target page accessibility tree using agent-browser snapshot, evaluate headings hierarchy, link integrity, and generate an accessibility report.',
    tags: ['Accessibility', 'SEO', 'Auditing'],
  },
];
